session: focus-test-app

root: /home/francis/Projects/focus-test-app

before_start:
  
stop:


windows:
  - name: code
    layout: main-horizontal
    commands:
      - nvim src/main.tsx
    panes:
      - type: horizontal
        commands:
          - t start
