session: preference-app 

root: /home/francis/Projects/preferences-app

before_start:
  
stop:


windows:
  - name: code
    layout: main-horizontal
    commands:
      - nvim
    panes:
      - type: horizontal
        commands:
          - t watch
      - type: vertical
