session: shell

root: ~/Projects/shell

before_start:

stop:

windows:
  - name: code
    root: .
    layout: main-horizontal
    commands:
      - nvim
    panes:
      - type: horizontal
        root: apps/shell-app
        commands:
          - t watch
      - type: vertical
        commands:
          - sh ~/.config/tmux/resize_term.sh
        root: .
