session: vue-components 

root: /home/francis/Projects/vue-components

before_start:
  
stop:


windows:
  - name: code
    layout: main-horizontal
    commands:
      - nvim
    panes:
      - type: horizontal
      - type: vertical
