#!/usr/bin/env bash

set -e
CONFIG_FILE="${CONFIG:-install.conf.yaml}"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_FILE}" -p "dotbot-npm/npm.py" -p "dotbot-git/git.py" "${@}"
