#!/bin/bash -ue

install() {
  ./install
}

app() {
  local prefix=""
  local force_flag=""
  local filename=""

  while getopts "p:t:f" option; do
    case ${option} in
    p) prefix="${OPTARG}/" ;;  # Prefix for the application
    f) force_flag="f" ;;       # Force flag
    t) filename="${OPTARG}" ;; # Filename
    \?)
      echo "Invalid option: ${OPTARG}" 1>&2
      return 1
      ;;
    :)
      echo "Option -${OPTARG} requires an argument." 1>&2
      return 1
      ;;
    esac
  done
  shift $((OPTIND - 1))

  export APP="$1"
  export CONFIG="stages/app.yaml"
  export DOT_APP_PREFIX="${prefix}"
  export DOT_APP_FILENAME="${filename}"

  if [ "${force_flag}" == "f" ]; then
    rm -f ".state/${DOT_APP_PREFIX}${APP}${DOT_APP_FILENAME}.skip"
    echo "Deleted .state/${APP}${DOT_APP_FILENAME}.skip"
  fi

  ./install
}

project() {

  local directory=""
  local force_flag=""
  local filename=""

  while getopts "d:t:f" option; do
    case ${option} in
    d) directory="${OPTARG}" ;; # Prefix for the application
    f) force_flag="f" ;;        # Force flag
    t) filename="${OPTARG}" ;;  # Filename
    \?)
      echo "Invalid option: ${OPTARG}" 1>&2
      return 1
      ;;
    :)
      echo "Option -${OPTARG} requires an argument." 1>&2
      return 1
      ;;
    esac
  done
  shift $((OPTIND - 1))

  export PROJECT=$1
  export PROJECT_DIR="${directory:-$PROJECT}"

  export CONFIG="stages/project.yaml"
  local FLAG="${3:-}"

  if [ "$FLAG" == "-f" ]; then
    rm ".state/$PROJECT_DIR/*.skip"
    echo "Deleted .state/$PROJECT_DIR/"
  fi

  ./install
}

project:new() {
  export PROJECT=$1
  export PROJECT_GIT=${2-}
  local FLAG="${3:-}"

  mkdir -p "${DOT_ENV}/projects/${PROJECT}/overlays"
  cp "apps/taskfile/config/Taskfile.template" "${DOT_ENV}/projects/${PROJECT}/overlays/Taskfile"
  chmod +x "${DOT_ENV}/projects/${PROJECT}/overlays/Taskfile"

  echo "$PROJECT_GIT" >"${DOT_ENV}/projects/${PROJECT}/git.repo"

  if [ "$FLAG" == "-i" ]; then
    ./Taskfile project "$PROJECT"
  fi
}

links() {
  CONFIG="stages/links.yaml" ./install
}

apps() {
  CONFIG="stages/apps.yaml" ./install
}

winhome() {
  CONFIG="winhome/install.yaml" ./install
}

wezterm:sync() {
  CONFIG="winhome/apps/wezterm/sync.yaml" ./install
}

wezterm:conf() {
  CONFIG="winhome/apps/wezterm/conf.yaml" ./install
}

work() {
  CONFIG="work/install.yaml" ./install
}

npm() {
  export CONFIG="stages/npm.yaml"
  local FLAG="${1:-}"

  if [ "$FLAG" == "-f" ]; then
    rm -f .state/npm.skip
    echo "Deleted .state/npm.skip"
  fi

  ./install
}

projects:run() {
  local cmd=${@:-pwd}
  find ~/Projects/ -maxdepth 1 -mindepth 1 -type d | while read d; do
    (
      cd $d/
      echo "Running command in $(pwd)"
      eval "$cmd"
    )

  done
}

projects:update() {
  projects:run "git pull && ni"
}

help() {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | cat -n | grep -v help | grep -v "_"
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"
