#!/bin/bash -ue

[[ -f "$HOME/.config/taskfile/MasterTaskfile" ]] && source "$HOME/.config/taskfile/MasterTaskfile"

install:pre() {
  sudo apt install zsh
  chsh -s $(which zsh)
  sudo apt install git build-essential
}

install() {
  install:pre &&
    ./install
}

app() {
  local FLAG="${2:-}"

  export APP="$1"
  export CONFIG="stages/app.yaml"

  if [ "$FLAG" == "-f" ]; then
    rm -f ".state/$APP.skip"
    echo "Deleted .state/$APP.skip"
  fi

  ./install

}

project() {
  export PROJECT=$1
  export PROJECT_DIR="${2:-$PROJECT}"

  export CONFIG="stages/project.yaml"
  local FLAG="${3:-}"

  if [ "$FLAG" == "-f" ]; then
    rm -f ".state/$APP.skip"
    echo "Deleted .state/$PROJECT_DIR-pre-install.skip"
    echo "Deleted .state/$PROJECT_DIR-post-install.skip"
  fi

  ./install
}

project:new() {
  export PROJECT=$1
  export PROJECT_GIT=${2-}
  local FLAG="${3:-}"

  mkdir -p "${DOT_ENV}/projects/${PROJECT}/overlays"
  cp "apps/taskfile/config/Taskfile.template" "${DOT_ENV}/projects/${PROJECT}/overlays/Taskfile"
  chmod +x "${DOT_ENV}/projects/${PROJECT}/overlays/Taskfile"

  echo "$PROJECT_GIT" >"${DOT_ENV}/projects/${PROJECT}/git.repo"

  if [ "$FLAG" == "-i" ]; then
    ./Taskfile project "$PROJECT"
  fi
}

links() {
  CONFIG="stages/links.yaml" ./install
}

apps() {
  CONFIG="stages/apps.yaml" ./install
}

winhome() {
  CONFIG="winhome/install.yaml" ./install
}

winhome:sync() {
  CONFIG="winhome/sync.yaml" ./install
}

work() {
  CONFIG="work/install.yaml" ./install
}

npm() {
  export CONFIG="stages/npm.yaml"
  local FLAG="${1:-}"

  if [ "$FLAG" == "-f" ]; then
    rm -f .state/npm.skip
    echo "Deleted .state/npm.skip"
  fi

  ./install
}

projects:run() {
  local cmd=${@:-pwd}
  find ~/Projects/ -maxdepth 1 -mindepth 1 -type d | while read d; do
    (
      cd $d/
      echo "Running command in $(pwd)"
      eval "$cmd"
    )

  done
}

projects:update() {
  projects:run "git pull && ni"
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"
