return {
  -- -- cmd = {...},
  -- -- filetypes { ...},
  -- -- capabilities = {},
  -- settings = {
  --   Lua = {
  --     runtime = { version = 'LuaJIT' },
  --     workspace = {
  --       checkThirdParty = false,
  --       -- Tells lua_ls where to find all the Lua files that you have loaded
  --       -- for your neovim configuration.
  --       library = {
  --         vim.env.VIMRUNTIME .. '/lua',
  --         '${3rd}/busted/library',
  --         '${3rd}/luv/library',
  --         wezterm,
  --       },
  --       -- If lua_ls is really slow on your computer, you can try this instead:
  --       -- library = { vim.env.VIMRUNTIME },
  --     },
  --     telemetry = {
  --       enable = false,
  --     },
  --     codeLens = {
  --       enable = false,
  --     },
  --     -- You can toggle below to ignore Lua_LS's noisy `missing-fields` warnings
  --     diagnostics = { disable = { 'missing-fields' } },
  --   },
  -- },
}
