return { -- Useful plugin to show you pending keybinds.
  'folke/which-key.nvim',
  config = function() -- This is the function that runs, AFTER loading
    require('which-key').setup({
      preset = 'modern',
    })

    -- Document existing key chains
    require('which-key').add({
      { '<leader>T', group = 'Tab' },
      { '<leader>T_', hidden = true },
      { '<leader>b', group = 'Buffer' },
      { '<leader>b_', hidden = true },
      { '<leader>c', group = 'Code/Copilot' },
      { '<leader>c_', hidden = true },
      { '<leader>d', group = 'Document' },
      { '<leader>d_', hidden = true },
      { '<leader>f', group = 'File' },
      { '<leader>f_', hidden = true },
      { '<leader>fy', group = 'Yank' },
      { '<leader>fy_', hidden = true },
      { '<leader>g', group = 'Git' },
      { '<leader>g_', hidden = true },
      { '<leader>gb', group = 'Branch' },
      { '<leader>gb_', hidden = true },
      { '<leader>gc', group = 'Commit' },
      { '<leader>gc_', hidden = true },
      { '<leader>gd', group = 'Diff' },
      { '<leader>gf', group = 'File' },
      { '<leader>gf_', hidden = true },
      { '<leader>gh', group = 'Hunk' },
      { '<leader>gh_', hidden = true },
      { '<leader>gl', group = 'Gitlab' },
      { '<leader>gl_', hidden = true },
      { '<leader>gp', group = 'Push/Pull' },
      { '<leader>gp_', hidden = true },
      { '<leader>gr', group = 'Rebase' },
      { '<leader>gr_', hidden = true },
      { '<leader>j', group = 'Jump', icon = { icon = '🦘', color = 'blue' } },
      { '<leader>j_', hidden = true },
      { '<leader>m', group = 'Macro' },
      { '<leader>m_', hidden = true },
      { '<leader>n', group = 'Notes', icon = { icon = '', color = 'blue' } },
      { '<leader>n_', hidden = true },
      { '<leader>p', group = 'Project' },
      { '<leader>p_', hidden = true },
      {
        mode = { 'v', 's' },
        { '<leader>r', group = 'Rename/Replace', icon = { icon = '🔁', color = 'blue' } },
        { '<leader>r_', hidden = true },
      },
      { '<leader>s', group = 'Search' },
      { '<leader>s_', hidden = true },
      { '<leader>t', group = 'Test' },
      { '<leader>t_', hidden = true },
      { '<leader>u', group = 'Ui' },
      { '<leader>u_', hidden = true },
      { '<leader>x', group = 'Execute' },
      { '<leader>x_', hidden = true },
      { '<leader>n_', hidden = true },
      { '<leader>p', group = 'Project', icon = { icon = '💻', color = 'blue' } },
      { '<leader>p_', hidden = true },
      { '<leader>s', group = 'Search' },
      { '<leader>s_', hidden = true },
      { '<leader>t', group = 'Test' },
      { '<leader>t_', hidden = true },
      { '<leader>u', group = 'Ui' },
      { '<leader>u_', hidden = true },
      { '<leader>x', group = 'Execute', icon = { icon = '🚀', color = 'blue' } },
      { '<leader>x_', hidden = true },
    })

    vim.cmd('doautocmd User WhichKeyAttach')
  end,
}
