require('custom.configs.options')
require('custom.configs.keymaps')
require('custom.configs.autocommands')
require('custom.configs.commands')
require('custom.configs.hacks')
require('custom.lib.marks').setup()
