# only this line might not be enough
set -g default-terminal "xterm-256color"

# Needs this line also to overrides the default color
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -sg escape-time 20
setw -g aggressive-resize on
set -g set-clipboard on
set -s set-clipboard on
set -g allow-passthrough on


# remap prefix to C-Space
unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# act like vim
# setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind / display-popup  -w80% -h75% -E "tmux new-session -A -s scratch -c \"#{pane_current_path}\""
bind C-i display-popup -E "sh ~/.config/tmux/list_session_fzf.sh"
bind C-o display-popup -E "sh ~/.config/tmux/open_session_fzf.sh"

bind-key -n C-p run-shell "~/.config/tmux/send_to_nvim.sh C-p"
bind-key -n C-b run-shell "~/.config/tmux/send_to_nvim.sh C-b"


# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Enable mouse control (clickable windows, panes, resizable panes)
set-option -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin "janoamaral/tokyo-night-tmux"

set -g status-position top


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
