#!/bin/bash -ue

[[ -f "$HOME/.config/taskfile/MasterTaskfile" ]] && source "$HOME/.config/taskfile/MasterTaskfile"

PATH=./node_modules/.bin:$PATH

start() {
  echo "start task not implemented"
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"
