#!/bin/bash -e

help() {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | cat -n | grep -v help | grep -v "_"
}

pack() {
  lpm pack
}

build:pack() {
  build && pack
}

update() {
  git pull &&
    ni
}

watch() {
  lpm watch -s -c "./Taskfile start"
}

lint() {
  nr lint
}

build() {
  nr build
}

install() {
  ni
}

tc() {
  nr typecheck
}

i() {
  ni
}
