- defaults:
    shell:
      stdout: true
      stderr: true
      quiet: true
- shell:
    - description: "📦📦📦 Application 📦📦📦"
      command: |
        if  [ -e ".state/${DOT_APP_PREFIX}${APP}${DOT_APP_FILENAME}.skip" ]; then
          echo "🔁 Skipping ${APP} install 🔁 \n"
          echo "file .state/${DOT_APP_PREFIX}${APP}${DOT_APP_FILENAME}.skip found\n"
        else
          CONFIG="${DOT_APP_PREFIX}apps/${APP}/${DOT_APP_FILENAME:-install}.yaml" ./install
          mkdir -p .state/${DOT_APP_PREFIX}
          touch .state/${DOT_APP_PREFIX}${APP}${DOT_APP_FILENAME}.skip
        fi
