- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
      stderr: true
      quiet: true

- create:
  - ".state/${PROJECT_DIR}/"

- shell:
    - echo "✨✨✨ Configuring Project ${PROJECT} ✨✨✨"
- shell:
    - description: "📦 Cloning or Pulling"
      command: |
        if  [ -d "$HOME/Projects/$PROJECT_DIR" ]; 
        then
          cd "$HOME/Projects/$PROJECT_DIR" 
          git pull;
        else
          if [ -z "$PROJECT_GIT" ]; then
            PROJECT_GIT=$(cat "${DOT_ENV}/projects/${PROJECT}/git.repo")
          fi
          git clone $PROJECT_GIT "$HOME/Projects/$PROJECT_DIR";
        fi

- link:
    ~/Projects/${PROJECT_DIR}/:
      glob: true
      force: true
      path: $DOT_ENV/projects/${PROJECT}/overlays/**/*

- link:
    ~/Projects/${PROJECT_DIR}/:
      glob: true
      force: true
      path: $DOT_ENV/projects/${PROJECT}/overlays/**/.*

- shell:
    - description: "📦 Pre install"
      command: |
        if  [ -e ".state/${PROJECT_DIR}/pre-install.skip" ]; then
           echo "😎 Skipping pre install"
        else
           if [ -f ${DOT_ENV}/projects/${PROJECT}/pre-install.yaml ]; then 
             CONFIG="${DOT_ENV}/projects/${PROJECT}/pre-install.yaml" ./install
           else
             echo "No pre install file ${DOT_ENV}/projects/${PROJECT}/pre-install.yaml"
           fi
           touch .state/${PROJECT_DIR}/pre-install.skip
        fi
 

- shell:
    - description: "📦 Installing"
      command: |
        if [ -f ~/Projects/${PROJECT_DIR}/package.json ]; then 
          cd ~/Projects/${PROJECT_DIR}
          ni
        fi


- shell:
    - description: "📦 Post install"
      command: |
        if  [ -e ".state/${PROJECT_DIR}/post-install.skip" ]; then
           echo "😎 Skipping post install"
        else
           if [ -f ${DOT_ENV}/projects/${PROJECT}/post-install.yaml ]; then
             CONFIG="${DOT_ENV}/projects/${PROJECT}/post-install.yaml" ./install
           else
             echo "No Post install file ${DOT_ENV}/projects/${PROJECT}/post-install.yaml"
           fi
           touch .state/${PROJECT_DIR}/post-install.skip
        fi


- shell:
    - echo "✨✨✨ End Configuring Project ${PROJECT} ✨✨✨"
