- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
      stderr: true
      quiet: true

- shell:
    - echo "✨✨✨ Configuring Project ${PROJECT} ✨✨✨"
- shell:
    - description: "📦 Cloning or Pulling"
      command: |
        if  [ -d "$HOME/Projects/$PROJECT" ]; 
        then
          cd "$HOME/Projects/$PROJECT" 
          git pull;
        else
          if [ -z "$PROJECT_GIT" ]; then
            PROJECT_GIT=$(cat "${DOT_ENV}/projects/${PROJECT}/git.repo")
          fi
          git clone $PROJECT_GIT "$HOME/Projects/$PROJECT";
        fi

- link:
    ~/Projects/${PROJECT}/:
      glob: true
      force: true
      path: $DOT_ENV/projects/${PROJECT}/overlays/**/*

- link:
    ~/Projects/${PROJECT}/:
      glob: true
      force: true
      path: $DOT_ENV/projects/${PROJECT}/overlays/**/.*

- shell:
    - description: "📦 Pre install"
      command: |
        if [ -f ${DOT_ENV}/projects/${PROJECT}/pre-install.yaml ]; then 
          CONFIG="${DOT_ENV}/projects/${PROJECT}/pre-install.yaml" ./install
        else
          echo "No pre install file ${DOT_ENV}/projects/${PROJECT}/pre-install.yaml"
        fi

- shell:
    - description: "📦 Installing"
      command: |
        if [ -f ~/Projects/${PROJECT}/package.json ]; then 
          cd ~/Projects/${PROJECT}
          ni
        fi


- shell:
    - description: "📦 Post install"
      command: |
        if [ -f ${DOT_ENV}/projects/${PROJECT}/post-install.yaml ]; then
          CONFIG="${DOT_ENV}/projects/${PROJECT}/post-install.yaml" ./install
        else
          echo "No Post install file ${DOT_ENV}/projects/${PROJECT}/post-install.yaml"
        fi

- shell:
    - echo "✨✨✨ End Configuring Project ${PROJECT} ✨✨✨"
